use_frameworks!

platform :ios, '8.0'

target 'WZAuthorKit_Category_Example' do
  pod 'WZAuthorKit_Category', :path => '../'

  target 'WZAuthorKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
